" Vim is better
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/vundle'

" Github bundles
Plugin 'sjl/badwolf'
Plugin 'mattn/webapi-vim'
Plugin 'mattn/gist-vim'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-commentary'
Plugin 'nvie/vim-flake8'
Plugin 'bling/vim-airline'
Plugin 'iynaix/django.vim'
Plugin 'kchmck/vim-coffee-script'
Plugin 'pangloss/vim-javascript'
Plugin 'tpope/vim-rails'
Plugin 'skammer/vim-css-color'
Plugin 'indenthtml.vim'
Plugin 'nginx.vim'
Plugin 'cakebaker/scss-syntax.vim'
Plugin 'wookiehangover/jshint.vim'
Plugin 'mklabs/grunt.vim'
" Plugin 'jnwhiteh/vim-golang'
Plugin 'fatih/vim-go'
Plugin 'vim-scripts/matchit.zip'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-markdown'

call vundle#end()
filetype plugin indent on

filetype detect
filetype on

" Always show the statusline
set laststatus=2

" Make fancy symbols w/ Powerline
let g:Powerline_symbols = 'fancy'

" Syntax highlighting
syntax on

" Syntax enabling?
syntax enable

" Show ruler line at bottom of each buffer
set ruler

" Show line numbers
set nu

" Highlight line w/ cursor
set cursorline

" Show additional info in the command line (very last line on screen) where
" appropriate.
set showcmd

" current mode in status line
set showmode

" < and > will hit indentation levels instead of always -4/+4
set shiftround

" Show matching brackets/parentheses when navigating around
set showmatch

" Change where splits show up
set splitbelow
set splitright

set colorcolumn=+1

set shell=zsh

" Default autoformatting options:
" t: automatically hard-wrap based on textwidth
" c: do the same for comments, but autoinsert comment character too
" r: also autoinsert comment character when making new lines after existing
" comment lines
" o: ditto but for o/O in normal mode
" q: Allow 'gq' to autowrap/autoformat comments as well as normal text
" n: Recognize numbered lists when autoformatting (don't explicitly need this,
" was probably in a default setup somewhere.)
" 2: Use 2nd line of a paragraph for the overall indentation level when
" autoformatting. Good for e.g. bulleted lists or other formats where first
" line in a paragraph may have a different indent than the rest.
set formatoptions=tcroqn2
" Start scrolling up/down when cursor gets to 3 lines away from window edge
set scrolloff=4
" Allow backspaces to eat indents, end-of-line/beginning-of-line characters
set backspace=indent,eol,start

" Make MacVim look less GUI-y
if has("gui_running")
    set guioptions=egmrt
endif

" Indentation levels. See :help tabstop for details.
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
" Keep indentation level from previous line
set autoindent
" Don't unindent when I press Enter on an indented line
set preserveindent
" 'smartindent', however, screws up Python -- so turn it off
set nosmartindent

" Wrap text after 79 characters
set textwidth=79

" Some changes in indentation, mostly for C-style languages and Ruby.
au BufRead,BufNewFile *.js,*.rb,*.cpp,*.h,*.html,*.css,*.coffee set shiftwidth=2
au BufRead,BufNewFile *.js,*.rb,*.cpp,*.h,*.html,*.css,*.coffee set tabstop=2
au BufRead,BufNewFile *.js,*.rb,*.cpp,*.h,*.html,*.css,*.coffee set softtabstop=2

" Use the below highlight group when displaying bad whitespace is desired.
highlight BadWhitespace ctermbg=red guibg=red

" Display tabs at the beginning of a line in Python mode as bad
" and make trailing whitespace be flagged as bad.
au BufRead,BufNewFile *.py,*.pyw match BadWhitespace /^\t\+/
au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/

" Go settings
au BufRead,BufNewFile *.go set noexpandtab
au BufRead,BufNewFile *.go set textwidth=0

" ----------------------------------------------------------------------------
" The following section contains suggested settings.  While in no way required
" to meet coding standards, they are helpful.

" Set the default file encoding to UTF-8: ``
set encoding=utf-8

" For full syntax highlighting:
let python_highlight_all=1

" Folding based on indentation: ``
set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=1
" ----------------------------------------------------------------------------
" Miscellaneous - mostly colors and keybinds
colorscheme badwolf
set t_Co=256

" Allow mouse
set mouse=a

" Mappings to make django syntax highlight switches easier.
" See: http://stevelosh.com/blog/2011/06/django-advice
nnoremap _dt :set ft=htmldjango<CR>
nnoremap _pd :set ft=python.django<CR>

" Auto-detect some django-y filenames
au BufNewFile,BufRead admin.py     setlocal filetype=python.django
au BufNewFile,BufRead urls.py      setlocal filetype=python.django
au BufNewFile,BufRead models.py    setlocal filetype=python.django
au BufNewFile,BufRead views.py     setlocal filetype=python.django
au BufNewFile,BufRead settings.py  setlocal filetype=python.django
au BufNewFile,BufRead forms.py     setlocal filetype=python.django

" Gist.vim settings
let g:gist_clip_command = 'pbcopy'
let g:gist_detect_filetype = 1
let g:gist_post_private = 1

" Tab navigation mappings
nmap <silent> <C-n> :tabnext<CR>
nmap <silent> <C-p> :tabprev<CR>
imap <silent> <C-n> <esc><C-n>
imap <silent> <C-p> <esc><C-p>

" Open NERDTree by default
" autocmd VimEnter * NERDTree
" autocmd VimEnter * wincmd p

" ----------------------------------------------------------------------------
command! -nargs=* -complete=file -bang Rename :call Rename("<args>", "<bang>")

function! Rename(name, bang)
    let l:curfile = expand("%:p")
    let l:curfilepath = expand("%:p:h")
    let l:newname = l:curfilepath . "/" . a:name
    let v:errmsg = ""
    silent! exec "saveas" . a:bang . " " . fnameescape(l:newname)
    if v:errmsg =~# '^$\|^E329'
        if expand("%:p") !=# l:curfile && filewritable(expand("%:p"))
            silent exec "bwipe! " . fnameescape(l:curfile)
            if delete(l:curfile)
                echoerr "Could not delete " . l:curfile
            endif
        endif
    else
        echoerr v:errmsg
    endif
endfunction


if !exists('g:airline_symbols')
let g:airline_symbols = {}
endif

" unicode symbols
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.whitespace = 'Ξ'
let g:airline_left_sep = '⮀'
let g:airline_left_alt_sep = '⮁'
let g:airline_right_sep = '⮂'
let g:airline_right_alt_sep = '⮃'
let g:airline_symbols.branch = '⭠'
let g:airline_symbols.readonly = '⭤'
let g:airline_symbols.linenr = '⭡'
