set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'

" Github bundles
Bundle 'sjl/badwolf'
Bundle 'mattn/gist-vim'
Bundle 'scrooloose/nerdtree'
Bundle 'tpope/vim-commentary'
Bundle 'nvie/vim-flake8'
Bundle 'Lokaltog/vim-powerline'
Bundle 'iynaix/django.vim'


filetype plugin indent on
filetype detect
filetype on

" Vim is better
set nocompatible

" Always show the statusline
set laststatus=2

" Make fancy symbols w/ Powerline
let g:Powerline_symbols = 'fancy'

" Syntax highlighting
syntax on

" Syntax enabling?
syntax enable

" Show ruler line at bottom of each buffer
set ruler

" Show line numbers
set nu

" Highlight line w/ cursor
set cursorline

" Show additional info in the command line (very last line on screen) where
" appropriate.
set showcmd

" current mode in status line
set showmode

" < and > will hit indentation levels instead of always -4/+4
set shiftround

" Show matching brackets/parentheses when navigating around
set showmatch

" Change where splits show up
set splitbelow
set splitright

set colorcolumn=+1

set shell=zsh

" Default autoformatting options:
" t: automatically hard-wrap based on textwidth
" c: do the same for comments, but autoinsert comment character too
" r: also autoinsert comment character when making new lines after existing
" comment lines
" o: ditto but for o/O in normal mode
" q: Allow 'gq' to autowrap/autoformat comments as well as normal text
" n: Recognize numbered lists when autoformatting (don't explicitly need this,
" was probably in a default setup somewhere.)
" 2: Use 2nd line of a paragraph for the overall indentation level when
" autoformatting. Good for e.g. bulleted lists or other formats where first
" line in a paragraph may have a different indent than the rest.
set formatoptions=tcroqn2
" Start scrolling up/down when cursor gets to 3 lines away from window edge
set scrolloff=4
" Allow backspaces to eat indents, end-of-line/beginning-of-line characters
set backspace=indent,eol,start

" Make MacVim look less GUI-y
if has("gui_running")
    set guioptions=egmrt
endif

" Indentation levels. See :help tabstop for details.
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
" Keep indentation level from previous line
set autoindent
" Don't unindent when I press Enter on an indented line
set preserveindent
" 'smartindent', however, screws up Python -- so turn it off
set nosmartindent

" Some changes in indentation, mostly for C-style languages and Ruby.
au BufRead,BufNewFile *.java,*.rb,*.cpp,*.h,*.html,*.css set shiftwidth=2
au BufRead,BufNewFile *.java,*.rb,*.cpp,*.h,*.html,*.css set tabstop=2

" Use the below highlight group when displaying bad whitespace is desired.
highlight BadWhitespace ctermbg=red guibg=red

" Display tabs at the beginning of a line in Python mode as bad
" and make trailing whitespace be flagged as bad.
au BufRead,BufNewFile *.py,*.pyw match BadWhitespace /^\t\+/
au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/

" Wrap text after 79 characters
set textwidth=79

" ----------------------------------------------------------------------------
" The following section contains suggested settings.  While in no way required
" to meet coding standards, they are helpful.

" Set the default file encoding to UTF-8: ``
set encoding=utf-8

" For full syntax highlighting:
let python_highlight_all=1

" Folding based on indentation: ``
set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=1
" ----------------------------------------------------------------------------
" Miscellaneous - mostly colors and keybinds
colorscheme badwolf
set t_Co=256

" Allow mouse
set mouse=a

" Mappings to make django syntax highlight switches easier.
" See: http://stevelosh.com/blog/2011/06/django-advice
nnoremap _dt :set ft=htmldjango<CR>
nnoremap _pd :set ft=python.django<CR>

" Auto-detect some django-y filenames
au BufNewFile,BufRead admin.py     setlocal filetype=python.django
au BufNewFile,BufRead urls.py      setlocal filetype=python.django
au BufNewFile,BufRead models.py    setlocal filetype=python.django
au BufNewFile,BufRead views.py     setlocal filetype=python.django
au BufNewFile,BufRead settings.py  setlocal filetype=python.django
au BufNewFile,BufRead forms.py     setlocal filetype=python.django

" Gist.vim settings
let g:gist_clip_command = 'xclip -selection clipboard'
let g:gist_detect_filetype = 1

" Tab navigation mappings
nmap <silent> <C-n> :tabnext<CR>
nmap <silent> <C-p> :tabprev<CR>
imap <silent> <C-n> <esc><C-n>
imap <silent> <C-p> <esc><C-p>
